# Nome do Workflow
name: DevOpsLab Pipeline

# Evento que irá acionar a pipeline
on: 
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.11'

      - name: Install Requirements
        run:  pip install flask
              
      - name: Unit Test
        run: python -m unittest -v test
    
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Autenticação no Google Cloud
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Deploy AppEngine
        id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v1'

      - id: 'test'
        run: 'curl "${{ steps.deploy.outputs.url }}"'